# Для раздела поставки
SUPPLY_WB_API_KEY = 'YOUR_TOKEN'
TARGET_WAREHOUSE_ID = [206348, 158311]  # склада Тула

# Коэффициенты (включительно)
MAX_NEED_COEFFICIENT = 5
MIN_NEED_COEFFICIENT = 0

NEED_BOX_TYPE_ID = 2

TELEGRAM_TOKEN = 'YOUR_TOKEN'
CHAT_IDs = ['', '', ]

TELEGRAM_TOKEN1 = 'YOUR_TOKEN'

# Для раздела аналитики
ANALYTICS_WB_API_KEY = 'YOUR_TOKEN'
SELLER_ID = 132681

#Для раздела продвижение
PROMOTION_WB_API_KEY = 'YOUR_TOKEN'

# Задержки
AFTER_ERROR_RESTART_DELAY_SEC = 15
DELAY_BETWEEN_WAREHOUSE_COEFFICIENTS_CHECK_SEC = 12
